version: '3.7'

services:

  ##
  ##  order
  ##
  order:
    image: manifest-service-order
    container_name: manifest-service-order
    ports:
      - "9000:5000"
      - "9001:50051"
    environment:
      - MANIFEST_CONFIG="{\"serviceMap\":{\"OrderService\":{\"hostname\":\"manifest-service-order\",\"port\":\"50051\"},\"UserService\":{\"hostname\":\"manifest-service-user\",\"port\":\"50051\"}}}"
  ##
  ##  user
  ##
  user:
    image: manifest-service-user
    container_name: manifest-service-user
    ports:
      - "9002:5000"
      - "9003:50051"
    environment:
      - MANIFEST_CONFIG="{\"serviceMap\":{\"OrderService\":{\"hostname\":\"manifest-service-order\",\"port\":\"50051\"},\"UserService\":{\"hostname\":\"manifest-service-user\",\"port\":\"50051\"}}}"
